Teknisk spesifikasjon for boligselskap.
Skatteetaten/api-dokumentasjon pull request #13
Opened 2024-05-07 10:23 UTC by heimmste

Teknisk spesifikasjon for boligselskap. Helt lik den for boligsameie.

2024-05-07 11:51 UTC, mikkel-naess requested changes

2024-05-07 11:51 UTC, mikkel-naess commented on docs/api/boligselskap.md
> +### Eksempel på respons
Savner eksempel på request her

2024-05-08 09:05 UTC, mikkel-naess requested changes

2024-05-08 09:05 UTC, mikkel-naess commented on docs/api/boligselskap.md
> +samme repsponsen. Kun det første av denne rekken med like API kall vil behandles. IdempotencyKey muliggjør at man trygt
Skrivefeil responsen*

2024-05-08 09:05 UTC, mikkel-naess commented on docs/api/boligselskap.md
> +  "leveranse": [
Mulig jeg ser feil her, men er ikke dette en boligsameie melding? Finner blant annet ikke boligselskapsformål..?

2024-05-08 10:00 UTC, heimmste commented on docs/api/boligselskap.md
> +  "leveranse": [
Det er en boligselskapsmelding. Den er til og med hentet fra ekom feeden :)
Hver oppgave har feks boenhet. Boenhet finnes ikke i boligsameie. Boligsameie har matrikkelnummer som ikke finnes i boligselskap.
Men du har rett i at det er felter som ikke er der. Det er jo uheldig i et eksempel kanskje. Kan legge til de som mangler.

2024-05-08 10:08 UTC, mikkel-naess commented on docs/api/boligselskap.md
> +#### Eksempel på innsending
Enig at vi bare burde ha med ett par oppgaver i eksempelet

2024-05-08 10:10 UTC, mikkel-naess commented on docs/api/boligselskap.md
> +  "leveranse": [
Ok, men som du sier, i så fall så mangler den vel noen felter. Er ganske sikker på at boligselskapsformål må på enten oppgave, leveranse eller begge. Hør gjerne med Jacob ang. dette, han har en oppgave på seg som går på å finne ut av hvordan det skal være. Er litt usikker på hvor langt han har kommet

2024-05-08 14:11 UTC, heimmste commented on docs/api/boligselskap.md
> +
Godt spørsmål. Dette er standardtekst fra de andre APIene. Men det er vel bedre å fjerne det hvis vi ikke vet om det faktisk stemmer.

2024-05-10 06:58 UTC, heimmste commented on docs/api/boligselskap.md
> +
Hvem vet dette mon tro?

2024-05-10 08:58 UTC, thomasaasen commented on docs/api/boligselskap.md
> +
Usikker. Men kanskje fjerne den "søk opp tjeneste"-delen da jeg tviler på at det er mulig 
Så får vi finne ut av dette etterhvert

2024-05-13 08:46 UTC, mikkel-naess approved these changes

2024-05-13 10:09 UTC, mikkel-naess approved these changes

2024-05-14 08:43 UTC, merged

2024-05-14 08:47 UTC, erik-nygren commented on docs/api/boligselskap.md
> +
Som prinsipp bør alle apier gjøres delegerbare slik at de som bruker systemleverandør kan få gjort dette. Det er nok også aktuelle selv der det er mest SBSer.