REALT-2506: Beskrivelse av boligsameie APIet til "Om tjenesten" siden.
Skatteetaten/api-dokumentasjon pull request #8
Opened 2024-05-02 12:59 UTC by heimmste

2024-05-02 13:55 UTC, jakenilsen requested changes

2024-05-02 13:55 UTC, jakenilsen commented on docs/api/boligsameie.md
> +boligsameier. Ett kall mot API-et er en rapportering for ett boligsameie git av en oppgavegiver og som gjelder ett
gitt*

2024-05-02 13:55 UTC, jakenilsen commented on docs/api/boligsameie.md
> +inntetktsår.
inntektsår

2024-05-02 13:55 UTC, jakenilsen commented on docs/api/boligsameie.md
> +API-et validerer mottate data mot JSON schema beskrevet på SwaggerHub. Se [feilkoder](boligsameie?tab=Feilkoder) for
mottatte

2024-05-02 13:55 UTC, jakenilsen commented on docs/api/boligsameie.md
> +identisk kall blir gjort 24 timer, eller senere, enn orginalkallet, blir det ikke regnet som et duplikat.
fjerne de 2 første kommaene:
"Hvis et identisk kall blir gjort 24 timer eller senere enn orginalkallet, blir det ikke regnet som et duplikat."

2024-05-02 13:55 UTC, jakenilsen commented on docs/api/boligsameie.md
> +Søk opp følgende tjeneste i Altinn for å delegere tilgangen: `Bolisameie API - På vegne av`
Boligsameie

2024-05-03 12:36 UTC, amund-hh-skatteetaten commented on docs/api/boligsameie.md
> +identisk kall blir gjort 24 timer eller senere enn originalkallet, blir det ikke regnet som et duplikat.
Burde vi kanskje si noe om at idempotensnøkkelen må genereres for hver unike innsending?

2024-05-03 13:34 UTC, mikkel-naess commented on docs/api/boligsameie.md
> +### Asynkron behandling av mottatte tredjepartsopplysninger
Syns ikke dette burde være med. Vi burde bare beskrive hvordan apiet skal brukes, hva det skal motta og beskrive tilbakemelding. Den asynkrone prosessen her er en del av intern behandling av dataene, og sånn sett ikke relevant for brukeren.

2024-05-03 13:38 UTC, mikkel-naess requested changes

2024-05-06 07:44 UTC, mikkel-naess requested changes

2024-05-06 07:44 UTC, mikkel-naess commented on docs/api/boligsameie.md
> +Bakgrunnen for idempotencyKey er at API-et av og til kalles med identiske data (samme
Setningen "Bakgrunnen for idempotencyKey er at API-et av og til kalles med identiske data (samme 
oppgavegiver, payload og parameterverdier) flere ganger innenfor et kort tidsrom" kan fjernes

2024-05-06 07:44 UTC, mikkel-naess commented on docs/api/boligsameie.md
> +API-et for boligsameie har bare ett endepunkt: Innsending. Dette endepunktet tar i mot tredjepartsopplysninger for
Lag beskrivelsen så lik som "Krav og betalinger API" som mulig:
API-et har 1 endepunkt:
- POST innsending: <Dette endepunktet.....>

2024-05-07 06:17 UTC, mikkel-naess requested changes

2024-05-07 06:33 UTC, heimmste commented on docs/api/boligsameie.md
> +å ha en ny idempotencyKey. For å forhindre unødvendig behandling av redundante kall vil API-et hoppe over alle kall med
Godt poeng :)

2024-05-07 07:47 UTC, mikkel-naess approved these changes

2024-05-07 09:38 UTC, jakenilsen approved these changes

2024-05-07 09:55 UTC, merged